management:
  endpoints:
    web:
      base-path: /management
  endpoint:
    health:
      show-details: when_authorized
      roles: 'ROLE_ADMIN'
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  application:
    name: Social Network Application

server:
  port: 8080
