management:
  server:
    port: 8081

  endpoint:
    probes:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  application:
    name: Social Network Application
  main:
    allow-bean-definition-overriding: true
  graphql:
    websocket:
      path: /graphql
  schema:
    locations:
      - classpath:/graphql/shared/
      - classpath:/graphql/greeting/
      - classpath:/graphql/user/
  neo4j:
    uri: neo4j+s://8903bc2e.databases.neo4j.io
    authentication:
      username: neo4j
      password: LnhaRqYKYgl_m9KemJgdpwZRdxojfZgxy9t1LgDYE1w
  data:
    neo4j:
      database: neo4j

server:
  port: 8080
  error:
    whitelabel:
      enabled: false

okta:
  oauth2:
    issuer: https://login.dev4fun.online/oauth2/default
