management:
  server:
    port: 8081

  endpoint:
    probes:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  application:
    name: Social Network Application

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
