apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "socivio-api.fullname" . }}
  labels:
    app: {{ template "socivio-api.name" . }}
    chart: {{ template "socivio-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "socivio-api.name" . }}
      release: {{ .Release.Name }}
  strategy:
    canary:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ template "socivio-api.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
              initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
              initialDelaySeconds: 60
          volumeMounts:
            - name: application-config
              readOnly: true
              mountPath: /usr/share/social-network/config
          envFrom:
            - secretRef:
                name: {{ include "socivio-api.fullname" . }}-env
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: application-config
          configMap:
            name: {{ template "socivio-api.fullname" . }}-config
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
