management:
  server:
    port: 8081

  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  application:
    name: Social Network Application
  main:
    allow-bean-definition-overriding: true

server:
  port: 8080

okta:
  oauth2:
    issuer: https://login.htcompany.xyz/oauth2/default

logging:
  level:
    com.htcompany: DEBUG

application:
  cors:
    allowed-origins:
      - http://localhost:4200
    allowed-methods: '*'
