management:
  server:
    port: 8081

  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

spring:
  application:
    name: Social Network Application
  main:
    allow-bean-definition-overriding: true
  graphql:
    websocket:
      path: /graphql
    cors:
      allowed-origins: http://localhost:4200
      allowed-methods: '*'
    schema:
      locations:
        - classpath:/graphql/shared/
        - classpath:/graphql/greeting/
        - classpath:/graphql/user/

  neo4j:
    uri: neo4j+s://c805f4ee.databases.neo4j.io
    authentication:
      username: neo4j
      password: byZfDFOcpSwASwKUCo8n5hyyUCR5SJCu3RxCS7ninkM
  data:
    neo4j:
      database: neo4j

server:
  port: 8080

okta:
  oauth2:
    issuer: https://login.dev4fun.online/oauth2/default
  client:
    token: 00p7rbQB1nbndrnJYFGEUJVjCV8OKbPo_OjgVnTczo
    org-url: https://login.dev4fun.online

logging:
  level:
    com.htcompany: DEBUG
    org.springframework.data.neo4j: DEBUG
