name: CD workflow

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - closed
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.sha }}"
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/setup

      - name: Build docker image
        uses: ./.github/build-image
        with:
          version: 0.0.1
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install apollo rover
        run: |
          curl -sSL https://rover.apollo.dev/nix/latest | sh
          echo "$HOME/.rover/bin" >> $GITHUB_PATH

      - name: Deploy to argocd
        uses: ./.github/deploy-argocd
        with:
          environment: dev
          version: 0.0.1
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          server: ${{ secrets.ARGOCD_SERVER }}
          username: ${{ secrets.ARGOCD_USERNAME }}
          password: ${{ secrets.ARGOCD_PASSWORD }}

      - name: Upload GraphQL Schema
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
        run: |
          rover graph publish Socivio-Graph@current --schema ./apps/sn-application/src/main/resources/graphql/schema.graphqls
