name: CI workflow

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.sha }}"
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      TESTCONTAINERS_HOST_OVERRIDE: 'localhost'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/setup

      - name: Lint
        run: yarn nx run-many --target=lint --all --parallel

      - name: Build
        run: yarn nx run-many --target=build --all --parallel

      - name: Run Tests
        run: yarn nx run-many --target=test --all --coverage --coverageReporters=json --parallel

      - name: Run e2e Tests
        env:
          AUTH_USERNAME: ${{ secrets.CI_AUTH_USERNAME }}
          AUTH_PASSWORD: ${{ secrets.CI_AUTH_PASSWORD }}
          AUTH2_USERNAME: ${{ secrets.CI_AUTH2_USERNAME }}
          AUTH2_PASSWORD: ${{ secrets.CI_AUTH2_PASSWORD }}
          OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
          OKTA_CLIENTID: ${{ secrets.OKTA_CLIENTID }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          API_URL: http://localhost:8080
        run: yarn nx run-many --target=e2e-ci --all --parallel

      - name: Merge Jest Reports
        run: |
          node ./tools/coverageMerger.js
          yarn nyc report --reporter lcov --report-dir coverage
          node ./tools/jestSonarMerger.js

      - name: Sonar Scan
        run: |
          ./gradlew testReport
          ./gradlew integrationTestReport
          ./gradlew codeCoverageReport
          ./gradlew sonarqube
