name: CI workflow

on:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/setup

      - name: Lint
        run: yarn nx run-many --target=lint --all --parallel

      - name: Build
        run: yarn nx run-many --target=build --all --parallel

      - name: Run Tests
        run: yarn nx run-many --target=test --all --coverage --coverageReporters=json --parallel

      - name: Run e2e Tests
        env:
          AUTH_USERNAME: ${{ secrets.CI_AUTH_USERNAME }}
          AUTH_PASSWORD: ${{ secrets.CI_AUTH_PASSWORD }}
          OKTA_DOMAIN: ${{ secrets.OKTA_DOMAIN }}
          OKTA_CLIENTID: ${{ secrets.OKTA_CLIENTID }}
        run: yarn nx run-many --target=e2e-ci --all --parallel

      - name: Sonar Scan
        run: |
          ./gradlew testReport
          ./gradlew integrationTestReport
          ./gradlew codeCoverageReport
          ./gradlew sonarqube
